[package]
name = "chessgraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0"
nom = "7.1.0"
uuid = { version = "0.8.2", features = ["v4"] }